name: Lint Dockerfiles

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - run: brew install hadolint

      - run: hadolint {3.16,3.17,3.18}/Dockerfile
